parameters:
    contact_email: '%env(CONTACT_EMAIL)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailerService:
        arguments:
            $contactEmail: '%contact_email%'

    App\Service\RecaptchaService:
        arguments:
            $siteKey: '%recaptcha_site_key%'
            $secretKey: '%recaptcha_secret_key%'
